#-----------RUTA PARA OBTENER TURISTA POR ID-----------
###
GET http://localhost:8000/api/turistas/1 HTTP/1.1
Accept: application/json


#-----------RUTA PARA AGREGAR ADMINISTRADOR-----------
###
POST http://localhost:8000/api/administrador HTTP/1.1
Content-Type: application/json

{
    "nombre": "summer",
    "correo": "summer@gmail.com",
    "password": "summer"
}


#-----------RUTA PARA INICIAR SESION DE ADMINISTRADOR-----------
###
POST http://localhost:8000/api/administrador/login HTTP/1.1
Content-Type: application/json

{
    "correo": "summer@gmail.com",
    "password": "summer"
}

#-----------RUTA PARA AGREGAR ESTABLECIMIENTO-----------
###
POST http://localhost:8000/api/establecimientos/rg HTTP/1.1
Content-Type: application/json
Authorization: Bearer 

{
    "idalta_establecimiento": 1,
    "nombre": "Restaurante del Mar",
    "direccion": "Calle del Sol, 123",
    "ciudad": "Marina",
    "tipo": "Restaurante",
    "horario": "12:00-22:00",
    "precio": "256",
    "imagen": "fondo-Spiderman.jpg"
}
