-- MySQL Script generated by MySQL Workbench
-- Fri Jun 27 08:58:58 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Tipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tipo` (
  `id_tipo` INT NOT NULL,
  `Nombre` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`id_tipo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`alta_estabecimiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`alta_estabecimiento` (
  `idalta_estabecimiento` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Direccion` VARCHAR(45) NULL,
  `Ciudad` VARCHAR(45) NULL,
  `id_tipo` INT NULL,
  `Horario` TIME NULL,
  `Precio` VARCHAR(45) NULL,
  `Imagen` MEDIUMTEXT NULL,
  PRIMARY KEY (`idalta_estabecimiento`),
  CONSTRAINT `id_tipo`
    FOREIGN KEY (`id_tipo`)
    REFERENCES `mydb`.`Tipo` (`id_tipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Rol` (
  `id_rol` INT NOT NULL,
  `nombre_rol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_rol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `id_usuario` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Correo` VARCHAR(45) NULL,
  `Password` VARCHAR(45) NULL,
  `id_rol` INT NULL,
  PRIMARY KEY (`id_usuario`),
  CONSTRAINT `Rol`
    FOREIGN KEY (`id_rol`)
    REFERENCES `mydb`.`Rol` (`id_rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `Rol_idx` ON `mydb`.`Usuario` (`id_rol` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`Destinos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Destinos` (
  `id_destinos` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Estado` VARCHAR(45) NULL,
  PRIMARY KEY (`id_destinos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Alertas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Alertas` (
  `id_alertas` INT NOT NULL,
  `id_usuario` INT NULL,
  `id_destino` INT NULL,
  `Mensaje` VARCHAR(45) NULL,
  `leido` BOOLEAN DEFAULT FALSE,
  PRIMARY KEY (`id_alertas`),
  CONSTRAINT `id_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `mydb`.`Usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_destino`
    FOREIGN KEY (`id_destino`)
    REFERENCES `mydb`.`Destinos` (`id_destinos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `id_usuario_idx` ON `mydb`.`Alertas` (`id_usuario` ASC);

CREATE INDEX `id_destino_idx` ON `mydb`.`Alertas` (`id_destino` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`Recomendaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Recomendaciones` (
  `id_recomendaciones` INT NOT NULL,
  `id_destino` INT NULL,
  `Mensaje` VARCHAR(45) NULL,
  PRIMARY KEY (`id_recomendaciones`),
  CONSTRAINT `fk_id_destino`
    FOREIGN KEY (`id_destino`)
    REFERENCES `mydb`.`Destinos` (`id_destinos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `id_destino_idx` ON `mydb`.`Recomendaciones` (`id_destino` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`Tipo_temporada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tipo_temporada` (
  `idTipo_temporada` INT NOT NULL,
  `nombre_temporada` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTipo_temporada`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Visitas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Visitas` (
  `id_visitas` INT NOT NULL,
  `fkid_destino` INT NULL,
  `fecha` DATE NULL,
  `cantidad` INT NULL,
  `origen` VARCHAR(45) NULL,
  PRIMARY KEY (`id_visitas`),
  CONSTRAINT `fk_visitas_destino`
    FOREIGN KEY (`fkid_destino`)
    REFERENCES `mydb`.`Destinos` (`id_destinos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `id_destino_idx` ON `mydb`.`Visitas` (`id_destino` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`Temporadas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Temporadas` (
  `id_temporadas` INT NOT NULL,
  `nombre` INT NULL,
  `fecha_inicio` DATE NULL,
  `fecha_fin` DATE NULL,
  `tipo_temporada` INT NULL,
  `estatus` INT NULL,
  PRIMARY KEY (`id_temporadas`),
  CONSTRAINT `tipo_temporada`
    FOREIGN KEY (`tipo_temporada`)
    REFERENCES `mydb`.`Tipo_temporada` (`idTipo_temporada`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_temporada`
    FOREIGN KEY (`tipo_temporada`)
    REFERENCES `mydb`.`Visitas` (`id_visitas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `id_temporada_idx` ON `mydb`.`Temporadas` (`tipo_temporada` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`Eventos_especiales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Eventos_especiales` (
  `idEventos_especiales` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Fecha_inicio` DATETIME NULL,
  `Fecha_final` DATETIME NULL,
  `Descripcion` VARCHAR(45) NULL,
  `estado_afectado` VARCHAR(45) NULL,
  `id_destino` INT NULL,
  `id_temporada` INT NULL,
  PRIMARY KEY (`idEventos_especiales`),
  CONSTRAINT `fk_eventos_destino`
    FOREIGN KEY (`id_destino`)
    REFERENCES `mydb`.`Destinos` (`id_destinos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_eventos_temporada`
    FOREIGN KEY (`id_temporada`)
    REFERENCES `mydb`.`Temporadas` (`id_temporadas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `id_destino_idx` ON `mydb`.`Eventos_especiales` (`id_destino` ASC);

CREATE INDEX `id_temporada_idx` ON `mydb`.`Eventos_especiales` (`id_temporada` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`Interracion_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Interracion_usuario` (
  `idInterracion_usuario` INT NOT NULL,
  `id_usuario` INT NULL,
  `id_destino` INT NULL,
  `tipo_interracion` VARCHAR(45) NULL,
  PRIMARY KEY (`idInterracion_usuario`),
  CONSTRAINT `fk_id_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `mydb`.`Usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_in_id_destino`
    FOREIGN KEY (`id_destino`)
    REFERENCES `mydb`.`Destinos` (`id_destinos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `id_usuario_idx` ON `mydb`.`Interracion_usuario` (`id_usuario` ASC);

CREATE INDEX `id_destino_idx` ON `mydb`.`Interracion_usuario` (`id_destino` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
